kotlin.code.style=official
kotlin.version=2.4.20
compose.version=1.12.0
compose.html.eap.enabled=true
systemProp.org.gradle.project.compose.html.eap.enabled=true
compose.html.eap.version=0.0.1+dev3
compose.html.eap.kotlinx-browser-common-subset.version=0.0.1+dev2
spring.boot.version=4.1.0
org.gradle.configuration-cache=true
org.gradle.caching=true
