package com.example.htmlcomparison.catalog

internal val FeaturedCatalogSections: List<ProjectCategory> = listOf(
    ProjectCategory(
        title = "Compose UI",
        slug = "compose-ui",
        projects = listOf(
            RankedProject(
                name = "compose-multiplatform",
                author = "JetBrains",
                stars = "19.3k",
                description = "Facilitates sharing UIs across iOS, Android, Desktop, and Web using a declarative framework. Provides high-performance UI rendering, native APIs access, and desktop-specific extensions. Includes libraries for web UI creation.",
                tags = listOf("#compose-ui", "#compose"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "Calendar",
                author = "kizitonwose",
                stars = "5.6k",
                description = "Highly customizable calendar library supporting single, multiple, and range date selection modes. Features include horizontal/vertical scrolling, heatmap calendar, custom views, and flexible date boundaries.",
                tags = listOf("#time-zone", "#scheduling", "#date-time"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "MIT License",
                grantWinner = false,
            ),
            RankedProject(
                name = "AboutLibraries",
                author = "mikepenz",
                stars = "4.4k",
                description = "Compiles dependency details and licenses at build time, offering APIs for easy visualization in apps. Features caching, comprehensive Gradle support, custom UI builds, compliance reports, and strict license mode.",
                tags = listOf("#license", "#dependency-management"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "haze",
                author = "chrisbanes",
                stars = "2.5k",
                description = "Background blurring for Compose Multiplatform / Jetpack Compose",
                tags = listOf("#compose-ui"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "Calf",
                author = "MohamedRejeb",
                stars = "1.6k",
                description = "Creates adaptive UIs for apps, providing components like alerts, bottom sheets, progress indicators, date/time pickers, and web views that adjust to the platform. Includes file picker and permission handling.",
                tags = listOf("#compose-ui"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "multiplatform-markdown-renderer",
                author = "mikepenz",
                stars = "1.0k",
                description = "Renders markdown content with easy setup, cross-platform support, and lightweight performance. Customizes styles, extended spans, and annotated strings. Integrates image loading and allows custom components.",
                tags = listOf("#compose"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
        ),
    ),
    ProjectCategory(
        title = "Local Storage",
        slug = "local-storage",
        projects = listOf(
            RankedProject(
                name = "sqldelight",
                author = "sqldelight",
                stars = "6.9k",
                description = "Generates typesafe APIs from SQL statements, verifies schema and migrations at compile-time, and enhances IDE with autocomplete and refactoring for simplified SQL management. Supports multiple SQL dialects.",
                tags = listOf("#storage", "#sqlite", "#database", "#data"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "room",
                author = "androidx",
                stars = "6.1k",
                description = "Abstraction layer over SQLite enabling robust database access, compile-time schema export and migrations, annotation-processor tooling, coroutine/RxJava/paging integrations, Gradle plugin for schema management.",
                tags = listOf("#test", "#sqlite", "#reactive", "#ksp", "#kotlin-coroutines", "#jetpack", "#gradle-plugin", "#database", "#code-generation"),
                platforms = listOf("JVM", "Kotlin/Native"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "Store",
                author = "MobileNativeFoundation",
                stars = "3.4k",
                description = "Typed repository for managing data flow from local and network sources, supporting CRUD operations, data validation, conversion, synchronization, and error tracking.",
                tags = listOf("#storage"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = true,
            ),
        ),
    ),
    ProjectCategory(
        title = "Navigation",
        slug = "navigation",
        projects = listOf(
            RankedProject(
                name = "navigation",
                author = "androidx",
                stars = "6.1k",
                description = "Simplifies navigation between UI destinations via a consistent API, offers type-safe arguments (Safe Args), Compose and fragment integrations, feature-module support, and testing utilities.",
                tags = listOf("#test", "#navigation", "#kotlin-serialization", "#jetpack", "#gradle-plugin", "#compose-navigation", "#compose", "#android-ui"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "navigation3",
                author = "androidx",
                stars = "6.1k",
                description = "Declarative navigation for Compose UIs, offering runtime and UI modules, navigation graphs, deep-linking, lifecycle-aware back stack handling, and simplified dependency setup.",
                tags = listOf("#navigation", "#jetpack", "#compose-navigation", "#compose", "#android-ui"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "navigationevent",
                author = "androidx",
                stars = "6.1k",
                description = "Unified API for system Back and Predictive Back events, simplifying back navigation and predictive gesture support across app components and lifecycles.",
                tags = listOf("#navigation", "#jetpack", "#api"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "voyager",
                author = "adrielcafe",
                stars = "3.1k",
                description = "Multiplatform navigation library seamlessly integrated with Jetpack Compose. Supports various navigation types including linear, bottom sheet, tab, nested, and multi-module navigation with state restoration, lifecycle callbacks, and deep linking.",
                tags = listOf("#compose-ui"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "MIT License",
                grantWinner = false,
            ),
        ),
    ),
    ProjectCategory(
        title = "Logging and testing",
        slug = "logging-and-testing",
        projects = listOf(
            RankedProject(
                name = "mockk",
                author = "mockk",
                stars = "5.8k",
                description = "Mocks library simplifies and automates unit testing by providing flexible, type-safe mocking capabilities. Key features include relaxed mocks, partial mocking, annotations for mock object creation, and support for various frameworks like JUnit and Spring.",
                tags = listOf("#test"),
                platforms = listOf("JVM"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "kotlin-logging",
                author = "oshai",
                stars = "3.1k",
                description = "Lightweight logging framework offering a performant logging facade with lazy-eval string logging, exception handling, and fluent logging style. Simplifies logger initialization and supports various SLF4J implementations.",
                tags = listOf("#logging"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "turbine",
                author = "cashapp",
                stars = "2.9k",
                description = "Small testing library for coroutines Flow. Offers awaitItem(), awaitComplete(), and awaitError() to test emitted items, completion, and errors. Allows standalone usage and custom timeouts, ensuring all events are consumed.",
                tags = listOf("#test"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "Kermit",
                author = "touchlab",
                stars = "1.0k",
                description = "Offers structured logging with configurable log levels, tagging, and output destinations. Supports logging to console, file, and custom destinations with flexible configuration options.",
                tags = listOf("#logging", "#debug"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
        ),
    ),
    ProjectCategory(
        title = "Utilities",
        slug = "utilities",
        projects = listOf(
            RankedProject(
                name = "kotlinx.coroutines",
                author = "Kotlin",
                stars = "13.8k",
                description = "Enables asynchronous programming with lightweight coroutines, offering structured concurrency, cancellation, and integration with various reactive streams and UI frameworks. Includes testing and debugging utilities.",
                tags = listOf("#concurrency", "#asynchronous"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "okio",
                author = "lysine-dev",
                stars = "9.0k",
                description = "Simplifies accessing, storing, and processing data by enhancing `java.io` and `java.nio` capabilities. Originated from OkHttp, ensuring robust performance for various data handling needs.",
                tags = listOf("#performance-optimization", "#file"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "arrow",
                author = "arrow-kt",
                stars = "6.6k",
                description = "Arrow is a set of libraries inspired by functional, data-oriented and concurrent programming, including typed errors and validation, coroutine and concurrency combinators, functional resource handling and resilience, immutable data manipulation (optics), and utilities for collections and functions.",
                tags = listOf("#validation", "#language-extensions", "#kotlin-coroutines", "#functional-programming", "#concurrency", "#arrow-kt"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Other",
                grantWinner = false,
            ),
            RankedProject(
                name = "kotlinx.serialization",
                author = "Kotlin",
                stars = "5.9k",
                description = "Enables reflectionless serialization for classes by generating visitor code through a compiler plugin, and includes a runtime library supporting various formats like JSON, Protobuf, CBOR, Hocon, and Properties.",
                tags = listOf("#serializer", "#json", "#data"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "kotlinx-datetime",
                author = "Kotlin",
                stars = "2.8k",
                description = "Facilitates seamless date and time operations with types like `Instant`, `LocalDateTime`, and `TimeZone`. Emphasizes minimalistic, pragmatic design, supporting ISO 8601 format and clear separation of physical and civil time.",
                tags = listOf("#kotlinx-datetime"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "kotlinx-io",
                author = "Kotlin",
                stars = "1.5k",
                description = "Offers basic IO primitives with a mutable `Buffer` for efficient data handling, `Source` and `Sink` interfaces for data streams, and experimental filesystem support via `FileSystem` and `Path` classes.",
                tags = listOf("#file"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
        ),
    ),
    ProjectCategory(
        title = "Networking",
        slug = "networking",
        projects = listOf(
            RankedProject(
                name = "ktor",
                author = "ktorio",
                stars = "14.5k",
                description = "Create asynchronous client and server applications. Anything from microservices to multiplatform HTTP client apps in a simple way. Open Source, free, and fun!",
                tags = listOf("#web", "#network", "#http"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "fuel",
                author = "kittinunf",
                stars = "4.6k",
                description = "Easiest HTTP networking library, leveraging coroutines for asynchronous operations. Supports custom configurations using OkHttpClient and NSURLSession, and fully compatible with R8/Proguard for Android.",
                tags = listOf("#network", "#http"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm"),
                license = "MIT License",
                grantWinner = false,
            ),
            RankedProject(
                name = "apollo-kotlin",
                author = "apollographql",
                stars = "4.0k",
                description = "Generates models from GraphQL queries, executes queries/mutations, and returns results as type-safe models. Features include query batching, HTTP and normalized caches, custom scalars, and file uploads.",
                tags = listOf("#network"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "MIT License",
                grantWinner = false,
            ),
            RankedProject(
                name = "Ktorfit",
                author = "Foso",
                stars = "2.1k",
                description = "HTTP client and symbol processor inspired by Retrofit, leveraging KSP and Ktor clients. Supports multiple platforms and includes annotations, core library, compiler plugin, and example projects.",
                tags = listOf("#network"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
        ),
    ),
    ProjectCategory(
        title = "Media",
        slug = "media",
        projects = listOf(
            RankedProject(
                name = "ComposeMediaPlayer",
                author = "kdroidFilter",
                stars = "487",
                description = "Video player library enables seamless playback across platforms, supporting local and URL-based files. Offers customizable UI, media controls, error handling, audio levels, and subtitle integration.",
                tags = listOf("#windows", "#macos", "#linux", "#compose-multiplatform"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "MIT License",
                grantWinner = false,
            ),
            RankedProject(
                name = "MediaPlayer-KMP",
                author = "KhubaibKhan4",
                stars = "305",
                description = "Enables seamless YouTube video and audio playback across multiple platforms, integrating with JetBrains Compose Multiplatform. Features include authentication tokens, event handling, and reels view support.",
                tags = listOf("#ui", "#service-sdk", "#desktop", "#compose-multiplatform", "#compose", "#authentication", "#audio"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "GNU General Public License v2.0",
                grantWinner = false,
            ),
        ),
    ),
    ProjectCategory(
        title = "Image loading",
        slug = "image-loading",
        projects = listOf(
            RankedProject(
                name = "coil",
                author = "coil-kt",
                stars = "11.9k",
                description = "Image loading library optimized for Android apps, featuring memory and disk caching, minimal boilerplate, and integration with modern libraries. Supports ImageView and Jetpack Compose with customizable requests.",
                tags = listOf("#network", "#image", "#graphics"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = true,
            ),
            RankedProject(
                name = "landscapist",
                author = "skydoves",
                stars = "2.6k",
                description = "Highly optimized, pluggable image loading solution for fetching and displaying network images using Glide, Coil, and Fresco. Supports tracing, custom implementations, animations (crossfades, blur), and configurable image-loading behaviors.",
                tags = listOf("#compose-ui"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "sketch",
                author = "panpf",
                stars = "2.4k",
                description = "Image loading library designed for Compose Multiplatform and Android View. Supports loading Image, GIF, SVG, Video thumbnails from the network, local, resources, and photo albums.",
                tags = listOf("#image-loader", "#compose-ui", "#animated-image"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
        ),
    ),
    ProjectCategory(
        title = "Dependency Injection",
        slug = "dependency-injection",
        projects = listOf(
            RankedProject(
                name = "koin",
                author = "InsertKoinIO",
                stars = "10.0k",
                description = "Pragmatic lightweight dependency injection framework using a DSL and light container. Offers packages for core, coroutines, testing, Android, Ktor, annotations, and Jetpack Compose integration. Includes tutorials and community support.",
                tags = listOf("#dependency-injection", "#architecture"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "Kodein",
                author = "kosi-libs",
                stars = "3.3k",
                description = "Straightforward dependency retrieval container offering lazy instantiation, binding, and debugging capabilities. Integrates with Android, Compose, and Ktor. Provides a simple, readable declarative DSL.",
                tags = listOf("#dependency-injection", "#architecture"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "MIT License",
                grantWinner = false,
            ),
            RankedProject(
                name = "kotlin-inject",
                author = "evant",
                stars = "1.5k",
                description = "Compile-time dependency injection library enabling seamless construction of type instances through annotations like `@Component`, `@Provides`, and `@Inject`. Supports component arguments, type alias differentiation, function injection, scopes, component inheritance, multi-bindings, assisted injection, lazy initialization, and default arguments.",
                tags = listOf("#dependency-injection"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "metro",
                author = "ZacSweers",
                stars = "1.4k",
                description = "Metro is a compile-time dependency injection framework that draws heavy inspiration from Dagger, Anvil, and Kotlin-Inject. It seeks to unify their best features under one, cohesive solution while adding a few new features and implemented as a compiler plugin.",
                tags = listOf("#dependency-injection", "#architecture"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
        ),
    ),
    ProjectCategory(
        title = "Remote data",
        slug = "remote-data",
        projects = listOf(
            RankedProject(
                name = "firebase-kotlin-sdk",
                author = "GitLiveApp",
                stars = "1.7k",
                description = "Offers a Kotlin-first SDK for Firebase, supporting multiplatform projects. Facilitates integration with various Firebase services using coroutines, flows, and Kotlin serialization, enhancing code readability and reducing boilerplate.",
                tags = listOf("#service-sdk"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "JS"),
                license = "Apache License 2.0",
                grantWinner = true,
            ),
            RankedProject(
                name = "supabase-kt",
                author = "supabase-community",
                stars = "839",
                description = "Client library for Supabase. Enables authentication, database interactions, storage, real-time features, and edge functions. Provides Apollo GraphQL integration, Compose Auth, and image loading with Coil. Includes various demos and tutorials.",
                tags = listOf("#service-sdk"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "MIT License",
                grantWinner = false,
            ),
        ),
    ),
    ProjectCategory(
        title = "Preferences",
        slug = "preferences",
        projects = listOf(
            RankedProject(
                name = "datastore",
                author = "androidx",
                stars = "6.1k",
                description = "Asynchronous, consistent, transactional storage replacing SharedPreferences; supports preferences and typed objects with Proto/JSON serialization, optional Rx adapters, and atomic updates.",
                tags = listOf("#storage", "#sharedpreferences", "#serializer", "#serialization", "#reactive", "#preferences", "#kotlin-serialization", "#jetpack", "#asynchronous"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "multiplatform-settings",
                author = "russhwolf",
                stars = "2.2k",
                description = "Library for persisting key-value data in common code across multiple platforms. Features include platform-specific settings implementations, factory classes, property delegates, listeners, and experimental support for serialization and coroutines.",
                tags = listOf("#storage"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = true,
            ),
            RankedProject(
                name = "ComposePreference",
                author = "zhanghai",
                stars = "320",
                description = "Implements a preference system with Material 3 design for Jetpack Compose, offering various preference types, theming options, and customizable data sources for flexible and efficient UI development.",
                tags = listOf("#preferences", "#compose-multiplatform", "#compose", "#android-ui"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
        ),
    ),
    ProjectCategory(
        title = "Web and HTML",
        slug = "web-and-html",
        projects = listOf(
            RankedProject(
                name = "kobweb",
                author = "varabyte",
                stars = "2.2k",
                description = "Opinionated framework for creating websites and web apps, leveraging Compose HTML. Features include live reloading, responsive design, static site exports, Markdown support, and server API routes.",
                tags = listOf("#web", "#compose-html", "#compose"),
                platforms = listOf("JVM", "JS"),
                license = "Apache License 2.0",
                grantWinner = true,
            ),
            RankedProject(
                name = "kotlinx.html",
                author = "Kotlin",
                stars = "1.7k",
                description = "Provides a DSL for building HTML to `Writer`, `Appendable`, or DOM, facilitating web development across various platforms. Enables direct HTML creation and DOM tree construction through intuitive syntax.",
                tags = listOf("#web", "#html"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "kvision",
                author = "rjaros",
                stars = "1.3k",
                description = "Builds modern web applications with object-oriented principles, offering a rich hierarchy of GUI components, support for reactive and imperative programming, type-safe DSL builders, and seamless integration with various frameworks and libraries.",
                tags = listOf("#web", "#ui"),
                platforms = listOf("JVM", "JS"),
                license = "MIT License",
                grantWinner = false,
            ),
        ),
    ),
    ProjectCategory(
        title = "Architectural",
        slug = "architectural",
        projects = listOf(
            RankedProject(
                name = "Decompose",
                author = "arkivanov",
                stars = "2.9k",
                description = "Breaks down code into tree-structured, lifecycle-aware business logic components with routing and pluggable UI support. Offers clear UI/non-UI separation, dependency injection, state preservation, and custom navigation models.",
                tags = listOf("#dependency-injection"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "circuit",
                author = "slackhq",
                stars = "1.8k",
                description = "Creates user interfaces with a declarative syntax, supports state management, and enhances UI development with reactive programming principles. Ideal for building scalable, maintainable applications.",
                tags = listOf("#ui"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "orbit-mvi",
                author = "orbit-mvi",
                stars = "1.3k",
                description = "Lightweight Redux/MVI-like library offering a simple, type-safe, coroutine-based API. Features include lifecycle-safe flow collection, ViewModel support, unit testing, espresso idling resources, and compatibility with RxJava and LiveData. Ideal for state management and side-effect handling.",
                tags = listOf("#dependency-injection"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = true,
            ),
        ),
    ),
    ProjectCategory(
        title = "Extended iOS support",
        slug = "extended-ios-support",
        projects = listOf(
            RankedProject(
                name = "KMP-NativeCoroutines",
                author = "rickclephas",
                stars = "1.3k",
                description = "Enables seamless use of coroutines from Swift in cross-platform apps. Solves cancellation support and generics limitations, generating code for async functions, AsyncStreams, Publishers, or Observables. Customizable naming and scope options.",
                tags = listOf("#asynchronous"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "MIT License",
                grantWinner = true,
            ),
            RankedProject(
                name = "SKIE",
                author = "touchlab",
                stars = "1.3k",
                description = "Enhances Swift API integration from Kotlin, reducing boilerplate code and improving maintainability for seamless cross-platform development. Valuable for modular projects and supports Compose Multiplatform integration.",
                tags = listOf("#graphics", "#gamedev"),
                platforms = listOf("JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "KMP-ObservableViewModel",
                author = "rickclephas",
                stars = "703",
                description = "Enables use of AndroidX ViewModels in SwiftUI, ensuring state changes propagate correctly. Provides wrappers for seamless integration with SwiftUI and supports creating and managing ViewModels across different platforms.",
                tags = listOf("#dependency-injection"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native", "Wasm", "JS"),
                license = "MIT License",
                grantWinner = false,
            ),
            RankedProject(
                name = "CrashKiOS",
                author = "touchlab",
                stars = "338",
                description = "Enables crash reporting, performance monitoring, and error tracking for iOS applications, offering detailed insights and diagnostics to improve app stability and user experience.",
                tags = listOf("#analytics"),
                platforms = listOf("Android JVM", "JVM", "Kotlin/Native"),
                license = "Apache License 2.0",
                grantWinner = false,
            ),
            RankedProject(
                name = "NSExceptionKt",
                author = "rickclephas",
                stars = "272",
                description = "Improves crash reports on Apple platforms by logging unhandled exceptions with detailed stack traces before app termination, enhancing visibility and debugging in production environments. Solves challenges of error handling differences and exception logging limitations.",
                tags = listOf("#analytics"),
                platforms = listOf("Kotlin/Native"),
                license = "MIT License",
                grantWinner = false,
            ),
        ),
    ),
)

